version: '3'

services:
  fastapi:
    build: backend/
    ports:
      - 2323:2323
    networks:
      - deploy_network
    container_name: fastapi

  streamlit:
    build: front/
    depends_on:
      - fastapi
    ports:
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit

networks:
  deploy_network:
    driver: bridge